### ISSUE TITLE
Do you have the trained model?

### ISSUE THREAD

**Issue by F2Wang** [ygjwd12345/Maskrcnn-hand#1]
Hi,
I would like to exam how well the hand detection works after training on the egohand dataset. Do you have the trained weight that you can send to me so that I can verify it directly without training myself?

My email is faninedinburgh@gmail.com

Thanks.

**Comment by SwithinHwong** [comment]
Same question, Would you provide the trained model and training dataset?

**Comment by ygjwd12345** [comment]
> Same question, Would you provide the trained model and training dataset?
I change the code from
https://github.com/matterport/Mask_RCNN,  you can download mask_rcnn_coco.h5.

**Comment by ygjwd12345** [comment]
I modify the code from https://github.com/matterport/Mask_RCNN, you can find the mask_rcnn_coco.h5 in there.

**Comment by ygjwd12345** [comment]
@F2Wang @SwithinHwong  I upload my trained model, you can find it form
https://drive.google.com/file/d/16aQPocdX8hHFkwRlMNIcNQQYEtGB5NyQ/view?usp=sharing. good like for you!!!

**Comment by SwithinHwong** [comment]
@ygjwd12345 Thanks for sharing the trained model! But it seems like public access premission is not set for the sharing, would you please allow public access?

**Comment by ygjwd12345** [comment]
@SwithinHwong  https://drive.google.com/file/d/16aQPocdX8hHFkwRlMNIcNQQYEtGB5NyQ/view?usp=sharing

**Comment by ygjwd12345** [comment]
@SwithinHwong  you should change labels to to fit maskrcnn input type

**Comment by ygjwd12345** [comment]
I have changed can you load normally?



发自我的iPhone


------------------ Original ------------------

**Comment by SwithinHwong** [comment]
Still downloading your model. I'll try it later today. Thanks!

**Comment by F2Wang** [comment]
Thank you for the model, I however get an size error on the fully connected layer 
ValueError: Layer #391 (named "mrcnn_bbox_fc"), weight <tf.Variable 'mrcnn_bbox_fc/kernel:0' shape=(1024, 324) dtype=float32_ref> has shape (1024, 324), but the saved weight has shape (1024, 8)
Have you encountered similar problem before?

**Comment by F2Wang** [comment]
Ignore my last question, I was being stupid, of course the fc layer will be different from the original since there are only 2 classes

**Comment by F2Wang** [comment]
Thank you for the trained model, the results appear quite reasonable, comparable to the refineNet result, when tested on my own dataset.

**Comment by iiiicode** [comment]
>Hello, could you please send me a copy of the pre-training model? Thank you very much

**Comment by iiiicode** [comment]
> Hello, could you please send me a copy of the pre-training model? Thank you very much

Hello, could you please send me a copy of the pre-training model? Thank you very much

**Comment by iiiicode** [comment]
> Still downloading your model. I'll try it later today. Thanks!

Hello, could you please send me a copy of the pre-training model? Thank you very much

**Comment by iiiicode** [comment]
> I modify the code from https://github.com/matterport/Mask_RCNN, you can find the mask_rcnn_coco.h5 in there.

Hello, could you please send me a copy of the pre-training model? Thank you very much

**Comment by ygjwd12345** [comment]
It is too long to find it.
